init python:
    sex_actions_data = {
        'anal_fuck':{'name': __("Anal penetration"),
        'pay':{'stamina': 1}, 'attribute': 'agility',  
        'markers':{'target': ['anal_stimulation', ], 'actor': ['straight', 'ass_fetish', ], 'both': []},
        'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
            'target':{'anatomy': ['body']}}},

        'struggle':{'name': __("Struggle"),
        'pay':{'stamina': 1}, 'attribute': 'physique',  
        'markers':{'target': ['forcing'], 'actor': ['active', 'restraint'], 'both': ['roughness',]},
        'required':{'actor':{'stats':{'feelings': ['<', 1]}, 'anatomy': ['graspers']},
            'target':{'willing': True, 'anatomy': ['graspers']}}},

        'endure':{'name': __("Endure violation"),
        'pay':{'drive': 1}, 'attribute': 'spirit',  
        'markers':{'target': ['active'], 'actor': ['passive'], 'both': []},
        'required':{'actor':{'willing': False},
            'target':{'willing': True}}},

        'suffer_pain':{'name': __("Suffer pain"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': ['active', 'sadism', ], 'actor': ['passive', 'masochism', ], 'both': ['roughness']},
        'required':{'actor':{'stats':{'feelings': ['<', 1]}},
            'target':{'willing': True}}}, 

        'suffer_shame':{'name': __("Suffer shame"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': ['abuse', 'passive', 'nothing', ], 'actor': ['humiliation', 'active', 'nothing', ], 'both': ['nothing', 'nothing', 'nothing', ]},
        'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
            'target':{'willing': True,'stats':{'feelings': ['>=', 1]}, 'anatomy': ['body']}}},

        'kiss':{'name': __("Kiss"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': [], 'actor': [], 'both': ['softness', 'orallove']},
        'required':{'actor':{'willing': True},
            'target':{'willing': True}}},

        'cunnilingus':{'name': __("Сunnilingus"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': ['orallove', 'passive', 'straight'], 'actor': ['sucker', 'active'], 'both': ['softness']},
        'required':{'actor':{'willing': True},
            'target':{'anatomy': ['vagina']}}},

        'fellation':{'name': __("Fellation"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': ['orallove', 'passive', 'straight'], 'actor': ['sucker', 'active'], 'both': ['softness']},
        'required':{'actor':{'willing': True},
            'target':{'anatomy': ['penis']}}},

        'rimming':{'name': __("Rimming"),
        'pay':{'drive': 1}, 'attribute': 'sensitivity',  
        'markers':{'target': ['orallove', 'passive', 'ttop'], 'actor': ['sucker', 'active', 'tbottom'], 'both': ['softness']},
        'required':{'actor':{'willing': True},
            'target':{'anatomy': ['body']}}},

        'fuck':{'name': __("Fuck"),
        'pay':{'stamina': 1}, 'attribute': 'agility',  
        'markers':{'target': [], 'actor': [], 'both': ['straight']},
        'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
            'target':{'anatomy': ['vagina']}}},




        'helpless_misery':{'name': __("Helpless misery"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['active', 'abuse'], 'actor': ['passive', 'humiliation'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['<', 1]}},
                'target':{'willing': True}}},

        'demand_to_stop':{'name': __("Demand to stop"),
            'pay':{'drive': 1}, 'attribute': 'spirit',  
            'markers':{'target': [], 'actor': [], 'both': ['dirtytalk']},
            'required':{'actor':{'stats':{'feelings': ['<', 1]}},
                'target':{'willing': True}}},

        'beg_to_stop':{'name': __("Beg to stop"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['abuse'], 'actor': ['humiliation'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['<', 1]}},
                'target':{'willing': True}}},

        'beg_for_mercy':{'name': __("Beg for mercy"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['abuse'], 'actor': ['humiliation'], 'both': ['sweettalk']},
            'required':{'actor':{'stats':{'feelings': ['<', 1]}},
                'target':{'willing': True}}},
                                
        'slap':{'name': __("Slap"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['masochism'], 'actor': ['sadism'], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{}}},

        'insult':{'name': __("Insult"),
            'pay':{'drive': 1}, 'attribute': 'spirit',  
            'markers':{'target': ['humiliation'], 'actor': ['abuse'], 'both': ['dirtytalk']},
            'required':{'actor':{'willing': True},
                'target':{}}},

        'spank':{'name': __("Spank"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['masochism', 'analstim'], 'actor': ['sadism', 'asslove'], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['body']}}},

        'bite':{'name': __("Bite"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['masochism', 'sucker'], 'actor': ['sadism', 'orallove'], 'both': ['roughness']},
            'required':{'actor':{'willing': True},
                'target':{'anatomy': ['body']}}},

        'tickle':{'name': __("Tickle"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['passive', 'restraint'], 'actor': ['active', 'forcing'], 'both': []},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['body']}}},

        'nipple_pinch':{'name': __("Nipple pinch"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['masochism', 'nipplestim'], 'actor': ['sadism', 'boobslove'], 'both': []},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers']},
                'target':{'anatomy': ['boobs']}}},
                
        'nipple_bite':{'name': __("Nipple bite"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['masochism', 'nipplestim', 'orallove'], 'actor': ['sadism', 'boobslove', 'sucker'], 'both': []},
            'required':{'actor':{'willing': True},
                'target':{'anatomy': ['boobs']}}},

        'nipple_caress':{'name': __("Nipple caress"),
            'pay':{'drive': 1}, 'attribute': 'agility',  
            'markers':{'target': ['nipplestim'], 'actor': ['boobslove'], 'both': ['softness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers']},
                'target':{'anatomy': ['boobs']}}},
                
        'nipple_suck':{'name': __("Nipple suck"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['nipplestim', 'orallove'], 'actor': ['boobslove', 'sucker'], 'both': ['softness']},
            'required':{'actor':{'willing': True},
                'target':{'anatomy': ['boobs']}}},
                
        'rough_kiss':{'name': __("Rough kiss"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['masochism', 'orallove'], 'actor': ['sadism', 'sucker'], 'both': ['roughness']},
            'required':{'actor':{'willing': True},
                'target':{}}},
                
        'choke':{'name': __("Choke"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive', 'restraint'], 'actor': ['active', 'forcing'], 'both': ['roughness', 'breath']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{}}},

        'caress':{'name': __("Caress"),
            'pay':{'drive': 1}, 'attribute': 'agility',  
            'markers':{'target': [], 'actor': [], 'both': ['softness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['body']}}},

        'fingering':{'name': __("Fingering"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['passive', 'straight'], 'actor': ['active'], 'both': []},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['vagina']}}},

        'fisting':{'name': __("Fisting"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive', 'straight', 'masochism'], 'actor': ['active'], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['vagina']}}},

        'ass_fingering':{'name': __("Ass fingering"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['passive', 'analstim'], 'actor': ['active', 'asslove'], 'both': []},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['body']}}},

        'ass_fisting':{'name': __("Ass fisting"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive', 'analstim', 'masochism', ], 'actor': ['active', 'asslove'], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'anatomy': ['graspers'] },
                'target':{'anatomy': ['body']}}},

        'soft_fuck':{'name': __("Soft fuck"),
            'pay':{'drive': 1}, 'attribute': 'agility',  
            'markers':{'target': [], 'actor': [], 'both': ['softness', 'straight']},
            'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
                'target':{'willing': True,'stats':{'feelings': ['>=', 1]}, 'anatomy': ['vagina']}}},

        'hard_fuck':{'name': __("Hard fuck"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive'], 'actor': ['active'], 'both': ['roughness', 'straight']},
            'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
                'target':{'anatomy': ['vagina']}}},
                
        'facefuck':{'name': __("Facefuck"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['passive', 'sucker'], 'actor': ['active', 'orallove', 'straight'], 'both': []},
            'required':{'actor':{'willing': True, 'anatomy': ['penis'] },
                'target':{}}},

        'forced_facefuck':{'name': __("Forced facefuck"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive', 'sucker', 'restraint'], 'actor': ['active', 'orallove', 'forcing', 'straight'], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
                'target':{}}},

        'hard_anal':{'name': __("Hard anal"),
            'pay':{'stamina': 1}, 'attribute': 'physique',  
            'markers':{'target': ['passive', 'analstim'], 'actor': ['active', 'asslove', 'straight', ], 'both': ['roughness']},
            'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
                'target':{'anatomy': ['body']}}},

        'orgasm':{'name': __("Orgasm"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': [], 'actor': ['straight', 'pleasure'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 5]}},
                'target':{}}},
                
        'sweet_pain':{'name': __("Sweet pain"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['sadism'], 'actor': ['masochism'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 5]}},
                'target':{'willing': True}}},

        'sweet_shame':{'name': __("Sweet shame"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['abuse'], 'actor': ['humiliation'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 5]}},
                'target':{'willing': True}}},

        'sweet_bondage':{'name': __("Sweet bondage"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['forcing'], 'actor': ['restraint'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 5]}},
                'target':{'willing': True}}},

        'pain_subspace':{'name': __("Pain subspace"),
            'pay':{'stamina': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['sadism'], 'actor': ['masochism', 'pleasure'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 10]}},
                'target':{'willing': True}}},

        'shame_subspace':{'name': __("Shame subspace"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['sadism'], 'actor': ['masochism', 'pleasure'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 10]}},
                'target':{'willing': True}}},

        'helpless_subspace':{'name': __("Helpless subspace"),
            'pay':{'drive': 1}, 'attribute': 'sensitivity',  
            'markers':{'target': ['sadism'], 'actor': ['masochism', 'pleasure'], 'both': []},
            'required':{'actor':{'stats':{'feelings': ['>=', 10]}},
                'target':{'willing': True}}},

        ##TEST
        'test':{'name': __("Test"),
            'pay':{'stamina': 1}, 'attribute': 'agility',  
            'markers':{'target': ['nothing', 'nothing', 'nothing', ], 'actor': ['nothing', 'nothing', 'nothing', ], 'both': ['nothing', 'nothing', 'nothing', ]},
            'required':{'actor':{'willing': True, 'stats':{'feelings': ['>=', 1]}, 'anatomy': ['penis'] },
                'target':{'willing': True,'stats':{'feelings': ['>=', 1]}, 'anatomy': ['body']}}},                                    
    }
